FROM bitnami/spark:3.5.0

COPY requirements.txt .

USER root

# RUN apt-get clean  && \
	#apt-get update --allow-releaseinfo-change && \
	# apt-get install -y --no-install-recommends python3 python3-pip && \
RUN	pip install -r requirements.txt --no-cache-dir 


